# AgriSense AI
## Smart Crop Recommendation & Agricultural Intelligence Platform

### Notebook 1: Data Cleaning & Feature Engineering

**Objective:**
- Load and inspect dataset
- Handle data quality issues
- Validate data types
- Detect duplicates and outliers
- Create domain-specific features
- Export cleaned dataset

In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [6]:
df = pd.read_csv("../data/Crop_recommendation.csv")

df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

## Dataset Shape

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 2200
Columns: 8

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
N,2200.0,50.551818,36.917334,0.000000,21.000000,37.000000,84.250000,140.000000
P,2200.0,53.362727,32.985883,5.000000,28.000000,51.000000,68.000000,145.000000
K,2200.0,48.149091,50.647931,5.000000,20.000000,32.000000,49.000000,205.000000
temperature,2200.0,25.616244,5.063749,8.825675,22.769375,25.598693,28.561654,43.675493
humidity,2200.0,71.481779,22.263812,14.258040,60.261953,80.473146,89.948771,99.981876
ph,2200.0,6.469480,0.773938,3.504752,5.971693,6.425045,6.923643,9.935091
rainfall,2200.0,103.463655,54.958389,20.211267,64.551686,94.867624,124.267508,298.560117

## Missing Values

In [10]:
df.isnull().sum()
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 0

## Duplicate Records

In [11]:
duplicates = df.duplicated().sum()

print("Duplicate Records:", duplicates)

Duplicate Records: 0

In [12]:
df = df.drop_duplicates()

## Crop Categories

In [13]:
print("Number of Crop Categories:")
df["label"].nunique()

Number of Crop Categories:

22

In [14]:
df["label"].unique()

array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

## Data Types

In [15]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

## Feature Engineering

In [16]:
df["NPK_Total"] = (
    df["N"] +
    df["P"] +
    df["K"]
)

In [17]:
df["NPK_Average"] = (
    df["N"] +
    df["P"] +
    df["K"]
) / 3

In [18]:
df["Humidity_Temp_Index"] = (
    df["humidity"] *
    df["temperature"]
)

In [19]:
df["Soil_Fertility"] = (
    0.4 * df["N"] +
    0.3 * df["P"] +
    0.3 * df["K"]
)

In [20]:
df["Rainfall_Category"] = pd.cut(
    df["rainfall"],
    bins=[0,100,200,400],
    labels=["Low","Medium","High"]
)

## Verify New Features

In [21]:
df.head()

,N,P,K,temperature,humidity,ph,rainfall,label,NPK_Total,NPK_Average,Humidity_Temp_Index,Soil_Fertility,Rainfall_Category
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,175,58.333333,1712.196283,61.5,High
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,184,61.333333,1748.595734,63.7,High
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,159,53.000000,1893.744627,53.7,High
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,149,49.666667,2123.482908,52.1,High
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,162,54.000000,1642.720357,56.4,High

In [22]:
df.shape

(2200, 13)

## Save Clean Dataset

In [23]:
df.to_csv(
    "../data/cleaned_crop_data.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [24]:
print("="*50)
print("DATA CLEANING COMPLETED")
print("="*50)

print("Final Shape:", df.shape)
print("Crop Categories:", df["label"].nunique())
print("Missing Values:", df.isnull().sum().sum())

==================================================
DATA CLEANING COMPLETED
==================================================
Final Shape: (2200, 13)
Crop Categories: 22
Missing Values: 0